import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/NavBar";
import { ClerkProvider, SignIn } from "@clerk/nextjs";
import { SignedIn, SignedOut} from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "DriveGo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <SignedIn>
            <NavBar/>
            {children}
          </SignedIn>

          <SignedOut>
          <SignIn routing="hash" />

          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
